### ISSUE TITLE
aenum 3.1.13 fails to import if sqlite3 does not exist

### ISSUE THREAD

**Issue by JelleZijlstra** [ethanfurman/aenum#30]
On a build of Python that lacks the `_sqlite` extension module, `aenum._enum.SqliteEnum` does not exist but it is still in `__all__`, breaking import:

```
>>> import aenum
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.pyenv/versions/3.9.13/lib/python3.9/site-packages/aenum/__init__.py", line 10, in <module>
    from ._enum import *
AttributeError: module 'aenum._enum' has no attribute 'SqliteEnum'
```

**Comment by ethanfurman** [comment]
Thanks.  Fixed in 3.1.14.
